const fs = require('node:fs');
const path = require('node:path');

const root = path.resolve(__dirname, '..');
const html = fs.readFileSync(path.join(root, 'index.html'), 'utf8');
const assets = new Set();
// Resource literals in the HTML, CSS and game script; tree names are constructed at runtime.
for (const match of html.matchAll(/["'](assets\/[^"'\r\n]+\.(?:png|jpg|jpeg|obj))(?:\?[^"'\r\n]*)?["']/g)) {
    assets.add(decodeURIComponent(match[1]));
}
for (let variant = 1; variant <= 4; variant++) {
    assets.add(`assets/environment/shop scene texture/t${variant}.png`);
}
const bundle = {};
for (const name of [...assets].sort()) {
    const file = path.resolve(root, name);
    if (!file.startsWith(root + path.sep)) throw new Error(`Invalid asset path: ${name}`);
    const data = fs.readFileSync(file);
    const extension = path.extname(file).toLowerCase();
    bundle[name] = extension === '.obj'
        ? data.toString('utf8')
        : `data:image/${extension === '.png' ? 'png' : 'jpeg'};base64,${data.toString('base64')}`;
}
const output = path.join(root, 'assets', 'offline-data.js');
fs.writeFileSync(output, '// Generated by node scripts/build-offline.cjs. Do not edit manually.\nwindow.offlineGameAssets = ' + JSON.stringify(bundle) + ';\n');
console.log(`Bundled ${assets.size} assets (${(fs.statSync(output).size / 1024 / 1024).toFixed(2)} MB).`);
